language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.4
    - RACKET_VERSION=6.5
    - RACKET_VERSION=6.6
    - RACKET_VERSION=6.7
    - RACKET_VERSION=6.8
    - RACKET_VERSION=6.9
    - RACKET_VERSION=6.10
    - RACKET_VERSION=HEAD

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  - raco pkg install --auto cover cover-codecov

install:
  - raco pkg install --auto $TRAVIS_BUILD_DIR/disposable
  - if [ "$RACKET_VERSION" == "6.10" ] || [ "$RACKET_VERSION" == "HEAD" ]; then raco pkg install --auto $TRAVIS_BUILD_DIR/disposable-test; fi

script:
  - if [ "$RACKET_VERSION" == "6.10" ] || [ "$RACKET_VERSION" == "HEAD" ]; then raco test -p disposable disposable-test; fi
  - if [ "$RACKET_VERSION" == "6.10" ] || [ "$RACKET_VERSION" == "HEAD" ]; then raco cover -f codecov -p disposable disposable-test; fi
