name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v1.11
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: 'current'
        sudo: never
        dest: '"${HOME}/racket"'
        local_catalogs: $GITHUB_WORKSPACE
    - run: raco pkg install --auto disposable disposable-test
    - run: raco test --package --drdr disposable disposable-test
