name: Resyntax Autofixer

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  autofix:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.6.0
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.9.1
        with:
          version: current
          local_catalogs: $GITHUB_WORKSPACE
          dest: '"${HOME}/racketdist-current-CS"'
          sudo: never
      - name: Install local packages
        run: raco pkg install --auto disposable disposable-test
      - name: Create a Resyntax pull request
        uses: jackfirth/create-resyntax-pull-request@v0.4.2
        with:
          private-key: ${{ secrets.RESYNTAX_APP_PRIVATE_KEY }}
